### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by malachibazar** [cardknox/vue-cardknox-ifields#4]
Hello,

I'm trying to get this npm module to work with Angular. I can import the module, but when I add `<ifields type="card" />` to my template, I get the following error:

`Only void and foreign elements can be self closed "ifields"`

I am running Angular 11.

Let me know if I need to give more information.

**Comment by mstein-ck** [comment]
Have you tried using a closing tag `<ifields type="card"></ifields>`?

**Comment by mstein-ck** [comment]
We will create a separate Angular component.
